config/routes.rb
Rails.application.routes.draw do
  # get 'edificio/index'
  # get 'edificio/show'
  # get 'edificio/new'
  # get 'edificio/edit'
  # get 'edificio/delete'
  # get 'departamento/index'
  # get 'departamento/show'
  # get 'departamento/new'
  # get 'departamento/edit'
  # get 'departamento/delete'

  # root 'edificio#index'
  
  # resources :edificio

  resources :edificios do
    member do
      get :delete
    end
  end

  resources :departamento do
    member do
      get :delete
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/departamento.rb
class Departamento < ApplicationRecord
  belongs_to :edificio

  validates :numero_departamento, presence: true , uniqueness: { case_sensitive: false}
    
  after_create :creacion_exitosa
  
  after_update :actualizacion_exitosa

  private
 
  
  def creacion_exitosa
      puts "Departamento creado con éxito"
  end
  
  def actualizacion_exitosa
      puts "Departamento actualizado con éxito"
  end
  
end

app/models/edificio.rb
class Edificio < ApplicationRecord
    has_has_many :departamentos, class_name: "departamento", foreign_key: "reference_id"
    validates :numero_edificio, :direccion, :ciudad, presence: true , uniqueness: { case_sensitive: false}
    
  after_create :creacion_exitosa
  
  after_update :actualizacion_exitosa

  private
 
  
  def creacion_exitosa
      puts "Departamento creado con éxito"
  end
  
  def actualizacion_exitosa
      puts "Departamento actualizado con éxito"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/departamento_controller.rb
class DepartamentoController < ApplicationController
  def index
    # @departamentos = Departamento.order(numero_departamento: :desc)
    @departamentos = Departamento.all
  end

  def show
    @departamento = Departamento.find(params[:id])
  end

  def new
  end

  def create 
  end

  def edit
  end

  def update 
  end

  def delete
  end

  def destroy 
  end

  private

  def departamento_params
    params.require(:departamento).permit(:numero, :edificio_id)
  end
end

app/controllers/edificio_controller.rb
class EdificioController < ApplicationController
  def index
    @edificios = Edificio.order(id: :desc)
  end

  def show
    @edificio = Edificio.find(params[:id])
    
  end

  def new
    @edificio = Edificio.new
  end

  def create 
    @edificio = Edificio.new(edificio_params)
    if @edificio.save 
      redirect_to(edificio_path)
    else
      render("new")
    end
  end

  def edit
  end

  def update 
  end

  def delete
  end

  def destroy 
  end


  private
  def edificio_params
    params.require(:edificio).permit(:nombre_edificio, :direccion, :ciudad)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departamento_helper.rb
module DepartamentoHelper
end

app/helpers/edificio_helper.rb
module EdificioHelper
end

app/views/departamento/delete.html.erb
<h1>Departamento#delete</h1>
<p>Find me in app/views/departamento/delete.html.erb</p>

app/views/departamento/edit.html.erb
<h1>Departamento#edit</h1>
<p>Find me in app/views/departamento/edit.html.erb</p>

app/views/departamento/index.html.erb
<%# <h1>Departamento#index</h1>
<p>Find me in app/views/departamento/index.html.erb</p> %>

<br>
<br>
<%= link_to "Ingresar Nuevo Departamento", new_departamento_path, :class=> "action new"%>

<table>
    <tr>
        <th>Número de Departamento</th>        
        <th>Edificio</th>        
        <th>Acciones</th>
    </tr>
        
    <% @departamentos.each do |i| %>                  
    <tr>
        <td><%=i.numero_departamento%></td>
        <td><%=i.edificio_id%></td>
        <td><%= link_to "Mostrar", departamento_path(i), :class=> "action show"%> </td>
    </tr>
    <% end %>

</table>
<br>

<%= link_to "Enlace 18-O", new_departamento_path%> 

app/views/departamento/new.html.erb
<h1>Departamento#new</h1>
<p>Find me in app/views/departamento/new.html.erb</p>

app/views/departamento/show.html.erb
<h1><%= @departamento.numero_departamento%></h1>
<p><%= @departamento.edificio_id%></p>

<%= link_to "Volver", departamento_path %>

app/views/edificio/delete.html.erb
<h1>Edificio#delete</h1>
<p>Find me in app/views/edificio/delete.html.erb</p>

app/views/edificio/edit.html.erb
<h1>Edificio#edit</h1>
<p>Find me in app/views/edificio/edit.html.erb</p>

app/views/edificio/index.html.erb
<%# <h1>Edificio#index</h1>
<p>Find me in app/views/edificio/index.html.erb</p> %>

<br>
<br>
<%= link_to "Agregar Nuevo Edificio", new_edificio_path, :class=> "action new"%>

<table>
    <tr>
        <th>Nombre</th>        
        <th>Dirección</th>
        <th>Ciudad</th>
        <th>Acciones</th>
    </tr>
        
    <% @edificios.each do |i| %>                  
    <tr>
        <td><%=i.nombre_edificio%></td>
        <td><%=i.direccion%></td>
        <td><%=i.ciudad%></td>
        <td><%= link_to "Mostrar", edificio_path(i), :class=> "action show"%> </td>
    </tr>
    <% end %>

</table>
<br>

<%= link_to "Agregar Nuevo Edificio", new_edificio_path%> 

app/views/edificio/new.html.erb
<br>
<br>

<%= link_to "Volver", :back %>
<h2>Crear nuevo Edificio</h2>
<%= form_for(@edificio, :url => new_edificio_path, :method => 'post') do |f|%>

<%= f.label :nombre%>
<td><%= f.text_field(:nombre_edificio)%></td>

<%= f.label :dirección%>
<td><%= f.text_field(:direccion)%></td>

<%= f.label :ciudad%>
<td><%= f.text_field(:ciudad)%></td>


<br>
<br>
<%= f.submit("Crear Edificio")%>
<%end%>

app/views/edificio/show.html.erb
<br>
<br>

<h1><%= @edificio.nombre_edificio%></h1>
<p><%= @edificio.direccion%></p>
<p><%= @edificio.ciudad%></p>
<br>
<%= link_to "Volver", :back %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ExamenJorgeandaur</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>